#!/bin/bash

cd ~/blog
source bin/activate
if [ -d "~/blog/build/output" ]; then
    cd ~/blog/build/output
    find . -type f -regextype posix-extended -regex ".*\.gz$" -exec rm {} \;
fi
cd ~/blog/build
make html
find . -type f -regextype posix-extended -regex ".*(\.html|\.css|\.xml)$" | parallel "gzip -c {} >{}.gz"
[ ! -d "~/blog/htdocs" ] || mkdir ~/blog/htdocs
rsync -a --delete output/* ~/blog/htdocs/
